apiVersion: v1
kind: Service
metadata:
  name: {{ include "idv.fullname" . }}-backoffice
  labels:
    {{- include "idv.backoffice.labels" . | nindent 4 }}
  {{- with .Values.backoffice.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backoffice.service.type }}
  ports:
    - port: {{ .Values.backoffice.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  {{- if .Values.backoffice.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.backoffice.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.backoffice.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.backoffice.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "idv.backoffice.selectorLabels" . | nindent 4 }}
