{{/* The purpose of this yaml file is it to check the values file is consistent for some complexe combinations. */}}

{{- /* SSL checks */ -}}
{{- if .Values.config.service.webServer.ssl.enabled }}
    {{- if not .Values.config.service.webServer.ssl.certificatesSecretName }}
        {{ required "When 'SSL' mode is enabled, config.service.webServer.ssl.certificatesSecretName value should be set." nil }}
    {{- end }}
{{- end }}

{{- /* Chip Verification checks */ -}}
{{- if  .Values.config.sdk.rfid.chipVerification.enabled }}
    {{- if not .Values.config.sdk.rfid.enabled }}
        {{ required "When 'Chip Verification' mode is enabled, `config.sdk.rfid.enabled` value should be set." nil }}
    {{- end }}
{{- end }}

{{- if and .Values.config.sdk.rfid.enabled .Values.config.sdk.rfid.chipVerification.enabled }}
    {{- if not (or .Values.config.service.database.connectionString .Values.config.service.database.connectionStringSecretName .Values.postgresql.enabled) }}
        {{ required "When 'Chip Verification' mode is enabled, `config.service.database.connectionString` or `config.service.database.connectionStringSecretName` or `postgresql.enabled` value should be set." nil }}
    {{- end }}
{{- end }}

{{- /* API v2 Verification checks */ -}}
{{- if .Values.config.service.sessionApi.enabled }}
    {{- if not (or .Values.config.service.database.connectionString .Values.config.service.database.connectionStringSecretName .Values.postgresql.enabled) }}
        {{ required "When 'Session API' mode is enabled, `config.service.database.connectionString` or `config.service.database.connectionStringSecretName` or `postgresql.enabled` value should be set." nil }}
    {{- end }}
{{- end }}
