apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docreader.config.name" . }}
  labels: {{- include "docreader.labels" . | nindent 4 }}
data:
  config.yaml: |+
    {{- include "docreader.config" . | nindent 4 }}
