{{- if .Values.ingress.enabled -}}
  {{- $serviceName := include "docreader.fullname" . -}}
  {{- $servicePort := .Values.service.port -}}
  {{- $paths := .Values.ingress.paths -}}
  {{- $pathType := .Values.ingress.pathType | default "Prefix" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "docreader.fullname" . }}
  labels: {{- include "docreader.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
        {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
        {{- end -}}
    {{- end -}}
  {{- else }}
    - http:
        paths:
        {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
        {{- end -}}
  {{- end -}}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
