{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "docreader.fullname" . }}
  labels:
    {{- include "docreader.labels" . | nindent 4 }}
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  policyTypes:
    {{- if .Values.networkPolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  podSelector:
    matchLabels:
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.networkPolicy.ingress }}
  ingress: {{- toYaml .Values.networkPolicy.ingress | nindent 4 -}}
  {{- end -}}
  {{- if .Values.networkPolicy.egress }}
  egress: {{- toYaml .Values.networkPolicy.egress | nindent 4 -}}
  {{- end -}}
{{- end }}
