{{/* The purpose of this yaml file is it to check the values file is consistent for some complexe combinations. */}}

{{- /* HTTPS checks */ -}}
{{- if .Values.https.enabled }}
    {{- if not .Values.https.certificatesSecretName }}
        {{ required "When 'HTTPS' mode is enabled, https.certificatesSecretName value should be set." nil }}
    {{- end }}
{{- end }}
