{{/* The purpose of this yaml file is it to check the values file is consistent for some complexe combinations. */}}

{{- /* HTTPS checks */ -}}
{{- if .Values.https.enabled }}
    {{- if not .Values.https.certificatesSecretName }}
        {{ required "When 'HTTPS' mode is enabled, https.certificatesSecretName value should be set." nil }}
    {{- end }}
{{- end }}

{{- /* Identification/Liveness related checks */ -}}
{{- /* Ensure PostgreSQL is enabled Identification or Liveness is enabled as well */ -}}
{{- if or .Values.postgresql.enabled .Values.externalPostgreSQL .Values.externalPostgreSQLSecret }}
    {{- if and (not .Values.liveness.enabled) (not .Values.identification.enabled) }}
    {{ required "'Identification/Liveness' modules or 'Liveness' module should be enabled before 'postgresql.enabled' OR 'externalPostgreSQL' OR 'externalPostgreSQLSecret' value is set." nil }}
    {{- end }}
{{- end }}

{{- /* Ensure Identification is enabled if Milvus is enabled */ -}}
{{- if and (not .Values.identification.enabled) .Values.milvus.enabled }}
    {{ required "'Identification' module should be enabled before 'milvus.enabled' value is set." nil }}
{{- end }}

{{- /* Ensure Identification related values are properly set */ -}}
{{- if .Values.identification.enabled }}
    {{- if not (or .Values.postgresql.enabled .Values.externalPostgreSQL .Values.externalPostgreSQLSecret) }}
        {{ required "When 'Identification' module is enabled, 'postgresql.enabled' OR 'externalPostgreSQL' OR 'externalPostgreSQLSecret' value should be set." nil }}
    {{- end }}
    {{- if and .Values.externalPostgreSQL .Values.externalPostgreSQLSecret }}
        {{ required "You must set one of the values externalPostgreSQL OR externalPostgreSQLSecret when using external postgreSQL." nil }}
    {{- end }}
    {{- if and .Values.postgresql.enabled (or .Values.externalPostgreSQL .Values.externalPostgreSQLSecret) }}
        {{ required "You must enable only 'postgresql.enabled' or use externalPostgreSQL/externalPostgreSQLSecret at a time." nil }}
    {{- end }}
    {{- if (not .Values.milvus.enabled) }}
        {{ required "When 'Identification' module is enabled, 'milvus.enabled' value should be set." nil }}
    {{- end }}
{{- end }}

{{- /* Ensure Liveness related values are properly set */ -}}
{{- if .Values.liveness.enabled }}
    {{- if not (or .Values.postgresql.enabled .Values.externalPostgreSQL .Values.externalPostgreSQLSecret) }}
        {{ required "When 'Liveness' module is enabled, 'postgresql.enabled' OR 'externalPostgreSQL' OR 'externalPostgreSQLSecret' value should be set." nil }}
    {{- end }}
    {{- if and .Values.externalPostgreSQL .Values.externalPostgreSQLSecret }}
        {{ required "You must set one of the values externalPostgreSQL OR externalPostgreSQLSecret when using external postgreSQL." nil }}
    {{- end }}
    {{- if and .Values.postgresql.enabled (or .Values.externalPostgreSQL .Values.externalPostgreSQLSecret) }}
        {{ required "You must enable only 'postgresql.enabled' or use externalPostgreSQL/externalPostgreSQLSecret at a time." nil }}
    {{- end }}
{{- end }}