apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "faceapi.config.name" . }}
  labels: {{- include "faceapi.labels" . | nindent 4 }}
data:
  config.yaml: |+
    {{- include "faceapi.config" . | nindent 4 }}
