{{- if and .Values.config.service.webServer.metrics.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "faceapi.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels: {{- include "faceapi.labels" . | nindent  4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent  4 }}
    {{- end }}
spec:
  endpoints:
    - honorLabels: true
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: /metrics
      port: faceapi
      {{- if .Values.config.service.webServer.ssl.enabled }}
      scheme: https
      {{- else }}
      scheme: http
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "faceapi.selectorLabels" . | nindent 6 }}
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
{{- end }}
