# apiVersion v2 is Helm 3
---
apiVersion: v2
name: faceapi
home: https://faceapi.regulaforensics.com/
version: 1.2.4
appVersion: 6.3.471.1180
description: Face Recognition Service. On-premise and cloud integration
icon: https://secure.gravatar.com/avatar/71a5efd69d82e444129ad18f51224bbb.jpg
keywords:
  - regula
  - faceapi
  - face-api
  - regulaforensics
dependencies:
  - name: postgresql
    version: 13.4.4
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: milvus
    version: 4.1.28
    repository: "https://zilliztech.github.io/milvus-helm/"
    condition: milvus.enabled
maintainers:
  - email: support@regulaforensics.com
    name: Regula Forensics Support
    url: https://support.regulaforensics.com
type: application
