name: CI

on:
  pull_request:
    branches: [main]

jobs:
  call-lint-test:
    uses: ./.github/workflows/lint-test.yml
    secrets:
      base64_value: ${{ secrets.REGULA_LICENSE }}
  call-chart-version:
    uses: ./.github/workflows/chart-version.yaml
